name: expand-validation
channels:
  - conda-forge
dependencies:
  - geopandas
  - rasterio
  - jupyterlab
  - python-dotenv
  - planet=1.5.2
  - boto3
  - matplotlib
  - scikit-image
  - pystac-client
  - dem_stitcher
<<<<<<< HEAD
  - tqdm
=======
  - papermill
  - notebook
>>>>>>> a8ad35f4bb241de3674d92fc019dc704cd462696
